version: 2

models:

  - name: stg_customers
    description: Cleaned customer staging model
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - not_null
          - unique

      - name: customer_name
        description: Customer name
        tests:
          - not_null


  - name: stg_products
    description: Cleaned product staging model
    columns:
      - name: product_id
        description: Unique product identifier
        tests:
          - not_null
          - unique

      - name: product_name
        description: Product name
        tests:
          - not_null


  - name: stg_orders
    description: Cleaned orders staging model
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - not_null
          - unique

      - name: customer_id
        description: Customer foreign key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: stg_customers.customer_id

      - name: product_id
        description: Product foreign key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_products')
                field: product_id

      - name: amount
        description: Order amount
        tests:
          - not_null